FROM php:8.2-cli

# Install curl and cron
RUN apt-get update && apt-get install -y \
    cron \
    curl \
    vim \
    nano && \
    rm -rf /var/lib/apt/lists/*

# Add your crontab file
COPY cron/crontab /etc/cron.d/my-cron

# Give execution rights
RUN chmod 0644 /etc/cron.d/my-cron

# Apply cron job
RUN crontab /etc/cron.d/my-cron

# Create a log file to be able to run tail
RUN touch /var/log/cron.log

# Start cron in the foreground
CMD ["cron", "-f"]

