version: '2.0'
services:
  web: # This will be the web access to the app
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: SOMESTRONGPASSWORD # Change this and take note, need to add it to config.json in /html
      MYSQL_DATABASE: screentime_db
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
  cron: # This is a light container to run the job that checks for devices to cut off
    build:
      context: .
      dockerfile: Dockerfile.cron
    depends_on:
      - db
